- name: ensure mongodb is running
  service: name=mongodb state=running enabled=yes

- name: add license file
  shell: "/bin/sh -c \"curl -s https://s3-eu-west-1.amazonaws.com/varnish-software-saas-terraform/license/license.vac -o /var/opt/vac/license.vac && chmod 0644 /var/opt/vac/license.vac && chown vac:vac /var/opt/vac/license.vac\""
  notify:
    - ensure vac is restarted

- name: ensure vstatd is running
  service: name=vstatd state=running enabled=yes

- name: ensure vac is running
  service: name=vac state=running enabled=yes