- file: path={{ vac_git_hooks_based_dir }} state=directory mode=0755

- name: prepare .vacrc configuration file
  template: src=vacrc.j2 dest={{ vac_git_hooks_based_dir }}/vacrc

- name: prepare vac_git_hooks.sh script
  copy: src=vac_git_hooks.sh dest={{ vac_git_hooks_based_dir }}/vac_git_hooks.sh mode=0755