- name: apply varnish-agent configuration
  template: src=varnish-agent.params.j2 dest=/etc/default/varnish-agent
  notify:
    - ensure varnish-agent is restarted

- name: ensure varnish-agent is running
  service: name=varnish-agent state=running enabled=yes