- name: Find a version of ansible
  shell: "/bin/sh -c \"ansible --version | grep ansible | awk '{print \\$2}'\""
  register: a_version

- include: more_than_v2.0.0.yml
  tags: vac-ansible-vcp-hosts
  when: a_version.stdout | version_compare('2.0.0','>=')

- include: less_than_v2.0.0.yml
  tags: vac-ansible-vcp-hosts
  when: a_version.stdout | version_compare('2.0.0','<')