- name: call Varnish API to get a list of caches
  shell: "/bin/sh -c \"curl -s -u {{ vac_root_user }}:{{ vac_root_passwd }} -X GET http://localhost/api/v1/cache | python -m json.tool | grep agentHost | tr -d '\\\",' | awk '{print \\$2}'\""
  register: vcp_nodes

- name: modify /etc/ansible/hosts file
  template: src=hosts.j2 dest=/etc/ansible/hosts