- name: apply varnish configuration
  template: src=varnish.j2 dest=/etc/default/varnish
  notify:
    - ensure varnish is restarted

- name: apply varnish-agent configuration
  template: src=varnish-agent.params.j2 dest=/etc/default/varnish-agent
  notify:
    - ensure varnish-agent is restarted

- name: apply vstatdprobe configuration
  template: src=vstatdprobe.params.j2 dest=/etc/default/vstatdprobe
  notify:
    - ensure vstatdprobe is restarted