varnish_listen_address: ''
varnish_listen_port: 80
varnish_admin_listen_address: 'localhost'
varnish_admin_listen_port: 6082
varnish_vcl_conf: '/etc/varnish/default.vcl'
varnish_secret_file: '/etc/varnish/secret'
varnish_storage: 'malloc,256m'
vcsprobe_remote_host_port: 5558
vcsprobe_max_queue: 50000