- name: Prepare get_groupoid script
  template: src=get_prod_groupoid.sh.j2 dest=/tmp/get_prod_groupoid.sh mode=0755

- name: Get PROD group id
  shell: /bin/sh /tmp/get_prod_groupoid.sh
  register: group_oid

#- name: Get PROD group id
#  shell: "/bin/sh -c \"curl -s -u {{ vac_root_user }}:{{ vac_root_passwd }} -X GET http://localhost/api/v1/group | jq '.list[0]._id[]' | tr -d '\\\"'\""
#  register: group_oid

- name: Get all VCP nodes
  shell: "/bin/sh -c \"curl -s -u {{ vac_root_user }}:{{ vac_root_passwd }} -X GET http://localhost/api/v1/cache | jq '.list[]._id[]' | tr -d '\\\"'\""
  register: vcp_nodes

- name: Register VCP nodes to PROD
  shell: curl -s -u {{ vac_root_user }}:{{ vac_root_passwd }} -X PUT http://localhost/api/v1/group/{{ group_oid.stdout }}/include/{{ item }}
  with_items: "{{ vcp_nodes.stdout_lines }}"

- name: Remove temp files
  file: path=/tmp/get_prod_groupoid.sh state=absent