- name: apply vstatd configuration
  template: src=vstatd.params.j2 dest=/etc/default/vstatd
  notify:
    - ensure vstatd is restarted

- name: ensure vstatd is running
  service: name=vstatd state=running enabled=yes