- name: check varnish-custom-statistics installed or not
  stat: path=/etc/varnish/vstatdprobe.params
  register: vstatdprobe_conf_file

- name: apply vstatdprobe configuration
  template: src=vstatdprobe.params.j2 dest=/etc/varnish/vstatdprobe.params
  when: vstatdprobe_conf_file.stat.exists == True
  notify:
    - ensure vstatdprobe is restarted

- name: ensure vstatdprobe is running
  service: name=vstatdprobe state=running enabled=yes
  when: vstatdprobe_conf_file.stat.exists == True
  ignore_errors: yes