#- name: ensure varnish-agent is restarted
#  service: name=varnish-agent state=restarted
- name: ensure varnish-agent is restarted
  shell: /usr/bin/pkill varnish-agent; sleep 2; service varnish-agent start