- name: apply default vha nodes configuration
  template: src=vha-agent.params.j2 dest=/etc/varnish/vha-agent.params

# - name: create a full list of registered cache nodes
#   shell: "/bin/sh -c \"for i in \$(curl -s -u vac:vac -X GET http://{{ vac_server }}:/api/v1/cache | python -m json.tool | grep agentHost | tr -d '\",' | awk '{print \$2}'); do echo \"node_\$(echo \$i | sed 's/\./_/g') = \$i\"; done > /tmp/nodes.conf\""

- name: canonify self ipv4 address
  shell: "/bin/sh -c \"echo \"{{ vha_self_ipv4_address }}\" | sed 's/\\./_/g'\""
  register: canonified_vha_self_ipv4_address

- name: canonify other node ipv4 address
  shell: "/bin/sh -c \"echo \"{{ vha_other_node }}\" | sed 's/\\./_/g'\""
  register: canonified_vha_other_node

- name: ensure /etc/vha-agent is presented
  file: path=/etc/vha-agent state=directory owner=root group=root mode=0755

- stat: path=/etc/vha-agent
  register: vha_agent_dir

- name: create vha-agent nodes.conf
  template: src=nodes.conf.j2 dest={{ vha_nodes_conf }}
  when: vha_agent_dir.stat.exists == True
  notify:
    - ensure vha-agent is restarted

- stat: path={{ vha_nodes_conf }}
  register: vha_node_conf_file

- name: create vha.vcl
  shell: "vha-agent -N {{ vha_nodes_conf }} -g > {{ vha_vcl }}"
  when: vha_node_conf_file.stat.exists == True
  notify:
    - ensure vha-agent is restarted

- stat: path={{ vha_vcl }}
  register: vha_vcl_file

- name: ensure vha.vcl is included to default.vcl
  template: src=default.vcl.j2 dest={{ varnish_default_vcl }}
  when: vha_vcl_file.stat.exists == True
  notify:
    - ensure varnish is restarted