- name: Get VAC user oid
  shell: "/bin/sh -c \"curl -s -u {{ vac_reset_root_user }}:{{ vac_reset_root_old_passwd }} -X GET http://localhost/api/v1/user | jq '.list[0]._id[]' | tr -d '\\\"'\""
  register: root_oid

- name: Get all info for JSESSIONID
  shell: "curl -s -X POST http://localhost/api/rest/login -H \"Content-T-www-form-urlencoded\" -d \"username=vac&password=1234\" -i"
  register: root_tmp

- name: Extract only JSESSIONID
  shell: echo {{ root_tmp.stdout_lines }} | grep -Po 'JSESSIONID=[\w.]+'
  register: root_jsessionid

- name: Apply a new password for VAC user
  shell: "curl -s -u {{ vac_reset_root_user }}:{{ vac_reset_root_old_passwd }} -X PUT http://localhost/api/v1/user/{{ root_oid.stdout }} -H \"Content-Type: application/json\" -H \"Cookie: {{  root_jsessionid.stdout }}\" -d \"{ \"username\" : \"{{ vac_reset_root_user }}\", \"password\" : \"{{ vac_reset_root_new_passwd }}\" }\""